using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TriangleMovement : MonoBehaviour
{
    // Start is called before the first frame update

    public Vector3 minPosition; //Min position vector
    public Vector3 maxPosition; //Max position vector

    public GameObject pointer; // Destination Object 
    public GameObject triangle; // Start Object

    Rigidbody2D rb;

    bool isMove = false;

    
    void Start()
    {
       
    }
    // Update is called once per frame
    void Update()
    {

        //Move start object to the destination object by using lerp and moveTowards method

         //triangle.transform.position = Vector2.MoveTowards(triangle.transform.position, pointer.transform.position, 10 * Time.deltaTime);
        triangle.transform.position = Vector2.Lerp(triangle.transform.position, pointer.transform.position, 2 * Time.deltaTime);

        if (Input.GetKeyDown(KeyCode.Space))
        {
            pointerGenerate();
        }

    }

    public void pointerGenerate()
    {

        // store the screen resolution top and bottom both converted into worldpoint 

        Vector2 worldBoundaryMax = Camera.main.ScreenToWorldPoint(new Vector2(Screen.width, Screen.height));
        Vector2 worldBoundaryMin = Camera.main.ScreenToWorldPoint(Vector2.zero);

        //Random position generated by using Random.Range()

       Vector2 randomPosition = new Vector2(
       Random.Range(worldBoundaryMin.x, worldBoundaryMax.x),
       Random.Range(worldBoundaryMin.y, worldBoundaryMax.y));
                       
        pointer.transform.position = randomPosition;


//**************************************************

        // first find the difference between start point to end point then apply the Atan2 formula
        // then convert to rediant to degree and get the actual Angle of boject

//***************************************************

      //  First way

       // Vector3 direction = pointer.transform.position - triangle.transform.position;
        //float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg - 90f;
        //triangle.transform.eulerAngles = Vector3.forward * angle;


        //Second way

        Vector3 look = triangle.transform.InverseTransformPoint(pointer.transform.position);
        float angle = Mathf.Atan2(look.y, look.x) * Mathf.Rad2Deg - 90f;
        triangle.transform.Rotate(0, 0, angle);

        //Third way
        //triangle.transform.up= pointer.transform.position - triangle.transform.position;

    }




}
